<?php
// ==========================================================
// classes/mailer.php — PHPMailer Wrapper Class
// ==========================================================

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require_once __DIR__ . '/../vendor/autoload.php';

class Mailer
{
    private $mail;

    public function __construct()
    {
        $this->mail = new PHPMailer(true);

        // SERVER SETTINGS
        $this->mail->isSMTP();
        $this->mail->Host = 'smtp.gmail.com';   // change if WMSU has SMTP server
        $this->mail->SMTPAuth = true;
        $this->mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        $this->mail->Port = 587;

        // CREDENTIALS
        $this->mail->Username = 'mathewpayopelin.payo.dev@gmail.com
';  
        $this->mail->Password = 'csmz bhta oltn ctik';     

        // DEFAULT FROM ADDRESS
        $this->mail->setFrom('mathewpayopelin.payo.dev@gmail.com
', 'WMSU Alumni Directory');
        $this->mail->isHTML(true);
    }

    // ======================================================
    // Send General Email
    // ======================================================
    public function sendEmail($to, $subject, $body, $altText = '')
    {
        try {
            $this->mail->clearAddresses();
            $this->mail->addAddress($to);

            $this->mail->Subject = $subject;
            $this->mail->Body    = $body;
            $this->mail->AltBody = $altText ?: strip_tags($body);

            return $this->mail->send();
        } catch (Exception $e) {
            error_log("Mailer Error: {$this->mail->ErrorInfo}");
            return false;
        }
    }

    // ======================================================
    // Send Verification Email
    // ======================================================
    public function sendVerificationEmail($email, $token)
    {
        $verifyUrl = "http://localhost/cssAlumniDirectorySystem/pages/auth/verify.php?token=" . $token;

        $subject = "Verify Your WMSU Alumni Directory Account";

        $body = "
            <h2>Verify Your Email</h2>
            <p>Please click the link below to verify your account:</p>
            <p><a href='{$verifyUrl}' style='background:#d32f2f;color:white;padding:10px 15px;text-decoration:none;'>Verify Account</a></p>
            <br>
            <p>If you did not request this, you may ignore this email.</p>
        ";

        return $this->sendEmail($email, $subject, $body);
    }

    // ======================================================
    // Send Password Reset Email
    // ======================================================
    public function sendPasswordResetEmail($email, $token)
    {
        $resetUrl = "http://localhost/cssAlumniDirectorySystem/pages/auth/resetPassword.php?token=" . $token;

        $subject = "WMSU Alumni Directory – Password Reset";

        $body = "
            <h2>Password Reset Request</h2>
            <p>Click below to reset your password:</p>
            <p><a href='{$resetUrl}' style='background:#d32f2f;color:white;padding:10px 15px;text-decoration:none;'>Reset Password</a></p>
            <br>
            <p>If you did not request this, you can ignore this email.</p>
        ";

        return $this->sendEmail($email, $subject, $body);
    }

    // ======================================================
    // Send Notification Email (Admin / User)
    // ======================================================
    public function sendNotification($email, $message)
    {
        $subject = "WMSU Alumni Directory Notification";

        $body = "
            <h3>Notification</h3>
            <p>{$message}</p>
            <br>
            <p>This message was automatically generated by the system.</p>
        ";

        return $this->sendEmail($email, $subject, $body);
    }
}
